apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: leosch1-leosch1-poi-backend-app-dev
  annotations:
    argocd/app-name: leosch1-leosch1-poi-backend-app-dev
    backstage.io/kubernetes-id: leosch1-leosch1-poi-backend-app-dev
    backstage.io/kubernetes-namespace: leosch1
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=leosch1-leosch1-poi-backend-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/leosch1-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/leosch1/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/leosch1/deployments/leosch1-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/leosch1-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/leosch1"
  system: workshop-system-leosch1
  providesApis:
    - backend-api-leosch1
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-leosch1
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/leosch1"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-leosch1
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://leosch1-poi-backend-app-leosch1.apps.summit23blues.6mbu.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/Summit23Janus2/leosch1-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/leosch1"
  system: workshop-system-leosch1
  definition:
    $text: https://github.com/Summit23Janus2/leosch1-backend/tree/main/src/main/resources/META-INF/openapi.yaml
